import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import InstallPWAButton from "@/components/custom/InstallButton";
import PopUpForCentreFest from "@/components/ad/PopUpForCentreFest";
import ClientWrapper from "./client-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Centre | A Student Led-Company for the Future",
  description: "Generated by Centre Web Team",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} bg-[var(--background)] text-[var(--foreground)]`}
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#3B82F6" />
      </head>
      <body className="min-h-screen flex flex-col font-sans relative">
        {/* ✅ Popup appears first so it overlays the whole site */}
        {/* <PopUpForCentreFest /> */}

        <ClientWrapper>{children}</ClientWrapper>

        {/* ✅ Install PWA Button */}
        <InstallPWAButton />
      </body>
    </html>
  );
}
